name: receiptocr
description: Extracts receipt texts using server side ocr and saves

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  edge_detection: ^1.0.9
  http: ^0.13.4
  photo_view: ^0.14.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
